#!/usr/bin/env bash
# Exit on error
set -eEuo pipefail

# shellcheck source=/dev/null
. ci/functions.sh

# Error handling
trap 'printf "\n\nERROR at $0 line $LINENO. Exiting.\n\n"' ERR

cfg_file="config.json"

# variable defaults
#---------------
script_name="${0##*/}"

c_name="$(jq -r '.api_versions.c_file' "${cfg_file}")"
h_name="$(jq -r '.api_versions.h_file' "${cfg_file}")"
struct_name="$(jq -r '.api_versions.struct_t' "${cfg_file}")"
project_name="$(jq -r '.api_versions.proj_name' "${cfg_file}")"
src_path="$(jq -r '.api_versions.path' "${cfg_file}")"
struct_t="$(jq -r '.api_versions.struct_t' "${cfg_file}")"
base_name="$(jq -r '.api_versions.base_name' "${cfg_file}")"
release="$(jq -r '.api_versions.release' "${cfg_file}")"

# Get latest git commit hash
g_hash=$(git rev-parse --short HEAD)
# Get git branch name
g_branch=$(git rev-parse --abbrev-ref HEAD)
# Get the git repo name
g_repo_name=$(git remote get-url origin)
g_local_changes='clean'

# Get git status to see if there are local changes not checked in

# shellcheck disable=SC2312
if [[ -n "$(git status --porcelain)" ]]; then
    warn "There are changes to commit in  ${g_repo_name}"
    g_local_changes="DIRTY"
fi
#g_changes=$(git status -s)
#info "${g_changes}"



# C file
auto_file="${src_path}/${c_name}"
mkdir -p "${src_path}"
cat > "${auto_file}" << EOF
/* clang-format off */
/**
 * \file ${c_name}
 * \brief ${project_name} firmware version, do not edit.
 * Automatically generated do not edit.
 * see ${script_name} for details
 */
#include "${h_name}"

/**
 * \brief Get the version
 * \return version structure pointer
 */
const ${struct_t}* ${base_name}_getInfo(void)
{
	static const ${struct_t} f_stVersion = {
		.pVersion       = "${release}",
		.pCommitHash    = "${g_hash}",
		.pBranch        = "${g_branch}",
		.pChanges       = "${g_local_changes}",
	};
    return &f_stVersion;
}
/* clang-format on */
EOF

# h file
auto_file="${src_path}/${h_name}"
cat > "${auto_file}" << EOF
/* clang-format off */
/**
 * \file ${h_name}
 * \brief ${project_name} firmware version, do not edit.
 * Automatically generated by:
 * ${script_name}"
 */
#ifndef ${base_name^^}_H__
#define ${base_name^^}_H__

#include <stdint.h>

#ifdef __cplusplus
  extern "C"
  {
#endif /*__cplusplus */


typedef struct{
    const char * pVersion;
    const char * pCommitHash;
    const char * pBranch;
    const char * pChanges;
} ${struct_name};


/**
 * \version Get the version
 * \return version structure pointer
 */
const ${struct_name}* ${base_name}_getInfo(void);


#ifdef __cplusplus
  }
#endif /*__cplusplus */
#endif /* ${base_name^^}_H__ */
/* clang-format on */
EOF

