/* clang-format off */
/**
 * \file autoVersion.h
 * \brief example firmware version, do not edit.
 * Automatically generated by:
 * generate-version-files.sh"
 */
#ifndef AUTOVERSION_H__
#define AUTOVERSION_H__

#include <stdint.h>

#ifdef __cplusplus
  extern "C"
  {
#endif /*__cplusplus */


typedef struct{
    const char * pVersion;
    const char * pCommitHash;
    const char * pBranch;
    const char * pChanges;
} st_auto_version_t;


/**
 * \version Get the version
 * \return version structure pointer
 */
const st_auto_version_t* autoVersion_getInfo(void);


#ifdef __cplusplus
  }
#endif /*__cplusplus */
#endif /* AUTOVERSION_H__ */
/* clang-format on */
