#!/usr/bin/env bash
# Exit on error
set -euo pipefail

# shellcheck source=/dev/null
. ci/functions.sh
# Error handling
trap 'printf "\n\nERROR at $0 line $LINENO. Exiting.\n\n"' ERR

test_list="./scripts/test/tests.json"
output_file="none"

usage() {
    cat <<Endofmessage

    Create a test version file for a target - not intended to be called
    directly, but rather by the run-tests.sh script.

    Use: $0 [-h] -t <target>

    optional arguments:

        -h display this help and exit

    TARGET:

        -t select the target to create the version file for.

Endofmessage

    jq -r '.serial | keys[]' "${test_list}" | while IFS= read -r key; do
        printf '            %s\n' "${key}"
    done

    cat <<Endofmessage

            ALL,            runs the test suite
Endofmessage
}

parse_args() {
    if [[ $# -eq 0 ]]; then
        usage
        fatal 1 'Please specify a target'
    fi
    while [[ $# -gt 0 ]]; do
        case $1 in
            -t)
                shift
                if [[ $# -eq 0 ]]; then
                    fatal 1 'Missing argument for -t'
                fi
                target=$1
                shift
                ;;
            -h)
                usage
                exit 0
                ;;
            -*|*)
                usage
                fatal 1 "Unknown option: $1"
                ;;
        esac
    done
}


get_target_variables(){
    type="serial"
    have_key="$(jq --arg key "${target}" '.serial | has($key)' "${test_list}")"
    if [[ "${have_key}" != true ]]; then
        fatal 1 "Target ${target} not found in serial tests"
    fi
    output_file=$(jq -r ".${type}.${target}.version_path" "${test_list}")
}


create_dummy_version_file() {
    cat >"${output_file}" <<EOF
/* This file is auto-generated by the build system. Do not edit manually. */
#ifndef VERSION_H__
#define VERSION_H__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus */

#define API_VERSION ("LOCAL")

#ifdef __cplusplus
}
#endif /*__cplusplus */

#endif /* VERSION_H__ */
EOF
}

create_version_file() {
    if [[ "${output_file}" == "none" ]]; then
        exit 0
    fi
    fw_list="./scripts/firmware/fw_list.json"
    target_name=$(jq -r --arg path "${output_file}" '.firmwares | to_entries[] | select(.value.version_path == $path) | .key' "${fw_list}" | head -n 1)
    info "Target name is ${target_name}"

    if [[ -n "${target_name}" ]]; then
        info "Target ${target_name} has a matching firmware, invoking create-fw-ver-file.sh to create the version file"
        info "./scripts/firmware/create-fw-ver-file.sh -t ${target_name}"
        ./scripts/firmware/create-fw-ver-file.sh -t "${target_name}"
    else
        info "Target ${target} does not have a matching firmware, creating a local version file"
        info "Creating version file ${output_file} for target ${target}"
        create_dummy_version_file
    fi
}

main() {
    parse_args "$@"
    get_target_variables
    create_version_file
}

main "$@"
