#!/usr/bin/env bash
#shellcheck disable=2312
# Exit on error
set -eEuo pipefail

# shellcheck source=/dev/null
source ci/functions.sh

# Error handling
trap 'printf "\n\nERROR at $0 line $LINENO. Exiting.\n\n"' ERR

cfg_file=./scripts/test/tests.json
env_file=./scripts/test/.testenv

cat << EOF > "${env_file}"

# automatically generated by $0

cc_ver="$(jq -r '.toolchain.gcc_version' "${cfg_file}")"
cppc_ver="$(jq -r '.toolchain.gpp_version' "${cfg_file}")"
GTEST_COLOR="$(jq -r '.toolchain.gtest_options.GTEST_COLOR' "${cfg_file}")"
GTEST_OUTPUT_ON_FAILURE=$(jq -r '.toolchain.gtest_options.GTEST_OUTPUT_ON_FAILURE' "${cfg_file}")
GTEST_OUTPUT="$(jq -r '.toolchain.gtest_options.GTEST_OUTPUT' "${cfg_file}")"
GTEST_BREAK_ON_FAILURE=$(jq -r '.toolchain.gtest_options.GTEST_BREAK_ON_FAILURE' "${cfg_file}")

EOF

info "Verify that no variables are assigned as null"
if grep -q '="null"' "${env_file}"; then
    fatal 1 "${env_file} file contains variables assigned to 'null'"
fi
