#!/usr/bin/env bash
#shellcheck disable=2312
# Exit on error
set -euo pipefail

# shellcheck source=/dev/null
. ci/functions.sh

# Error handling
trap 'err "ERROR at $0 line ${BASH_LINENO[0]}. Exiting."; exit 1' ERR

cfg_file=config.json
env_file=.env

cat <<EOF >"${env_file}"
# automatically generated by $0

# development docker image
DKR_FW_IMAGE_NAME="$(jq -r '.fw_dev_image.name' "${cfg_file}")"
DKR_FW_FILE="$(jq -r '.fw_dev_image.file' "${cfg_file}")"
DKR_FW_BLD_CONTEXT="$(jq -r '.fw_dev_image.context' "${cfg_file}")"
DKR_FW_USER="$(jq -r '.fw_dev_image.username' "${cfg_file}")"

USER_ID="$(id -u)"
GROUP_ID="$(id -g)"

# base image dependencies
CI_BASE_IMAGE="$(jq -r '.fw_dev_image.base' "${cfg_file}")"

EOF

info "Verify that no variables are assigned as null"
if grep -q '="null"' "${env_file}"; then
    fatal 1 "${env_file} file contains variables assigned to 'null'"
fi
